version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: promptlyzer-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=promptlyzer_os
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - promptlyzer-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/promptlyzer_os --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: promptlyzer-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/promptlyzer_os
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - promptlyzer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promptlyzer-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - promptlyzer-network

networks:
  promptlyzer-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local